name: matrix Demo
on: push

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node_version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-versin: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version}}
      - name: Install Dependencies
        run : npm ci
      - name: Build project
        run: npm run build
